name: Build and Push to Dockerhub

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  container:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Dockerhub
        uses: docker/login-action@v4
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and Push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: sandeshkhadka/roommates-frontend:latest
